### ISSUE TITLE
point, pose allocation efficiency

### ISSUE THREAD

**Issue by kemfic** [kemfic/ficiciSLAM#5]
for loop here is unnecessary, just accumulate newer frame pose and points as each frame processes, instead of just adding everything during each frame.

might reuse it later for bundle adjustment and map optimization events.

https://github.com/kemfic1/ficiciSLAM/blob/ec3a72fb8d431a37edf9c73a6a017758a2be9cca/viewer.py#L99-L111

**Comment by kemfic1** [comment]
Changed it up a bit, this should fix it for now.

**Comment by kemfic1** [comment]
Try np.tensordot for points

**Comment by kemfic** [comment]
np.dot(pts, Rt.T) seems to do the trick

[mentioned here](https://github.com/matthew-brett/transforms3d/blob/2b2cc5f95ec4323e184f798f984aa622cfaf6fc8/original/transformations.py#L65-L68)

[fixed code](https://github.com/kemfic/ficiciSLAM/blob/6d419ddb7153b1b987e23e3ee5fba5f74ef6c2a1/viewer.py#L109-L110)

**Comment by kemfic** [comment]
program now runs at ~30fps instead of the previous ~0.25fps

5d756118130074ff6dd495dd184f7ec3a6e4ab40
